---
# https://github.com/super-linter/super-linter
name: super-linter

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - uses: super-linter/super-linter@v5
        # env:
        #   VALIDATE_TERRAGRUNT: false
